In [5]:
import pandas as pd
import numpy as np
import matplotlib as plt
%matplotlib inline 

In [20]:
# 1st Problem statement 
def Alexandre_Theophile_Vandermonde(x):
    Y = np.vander(x, N=None, increasing=False)
    return Y

In [21]:
# This is the sample of the input
x = np.array ([1,2,4,6])

In [22]:
Alexandre_Theophile_Vandermonde(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 64,  16,   4,   1],
       [216,  36,   6,   1]])

In [9]:
# 2nd Problem statement 
def moving_average(a, n=3) :
    asum = np.cumsum(a, dtype=float)
    asum[n:] = asum[n:] - asum[:-n] 
    return asum[n - 1:] / n

In [10]:
a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

In [11]:
moving_average(a, 3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

In [14]:
b=[10,20,30,40,50,60,70,80,90,100]

In [15]:
moving_average(b, 4)

array([25., 35., 45., 55., 65., 75., 85.])